version: '3'
services:
  flask:
    container_name: flask_demo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5050:5050
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0 -p 5050